plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '5.1.+'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = "${mod_version}"
group = 'chappie.theboys'
archivesBaseName = 'theboys'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

minecraft {
    mappings channel: 'parchment', version: "2023.06.26-1.19.4"
    //mappings channel: 'parchment', version: "2023.03.12-${minecraft_version}"
    //mappings channel: 'official', version: "${minecraft_version}"

    //accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN, REGISTRIES, REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'theboys'
            mods {
                theboys {
                    source sourceSets.main
                }
            }
        }
        client {}
        clientWithCredentials {
            parent runs.client
            args '--username', 'ChappiePie', '--uuid', '8464971c-f5ac-4eb5-87aa-511a0eec65f6'
        }
        clientWithCredentials2 {
            parent runs.client
            args '--username', 'SEMASEM', '--uuid', '33ef476e-f075-45fb-8c22-9ecd6483abd3'
        }
        server {}
        data {
            args '--mod', 'theboys', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    maven { url 'https://jitpack.io' }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
    }
    maven {
        name = 'BlameJared Maven (CrT / Bookshelf)'
        url = 'https://maven.blamejared.com'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation fg.deobf("chappie.modulus:modulus:${core_version}")
    compileOnly(annotationProcessor("com.github.llamalad7.mixinextras:mixinextras-common:${mixin_extras_version}"))
    compileOnly(fg.deobf("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}"))

//    if (System.getProperty('idea.sync.active') != 'true') {
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
//    }

    /*implementation("foundry.veil:Veil-forge-1.19.2:1.0.0.145") {
        exclude group: "maven.modrinth"
    }*/


}

mixin {
    add sourceSets.main, "theboys.refmap.json"
    config 'theboys.mixins.json'
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "theboys",
                "Specification-Vendor"    : "theboyssareus",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "theboyssareus",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
