buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '3.+', changing: true
    }
}

apply plugin: 'java'
apply plugin: "eclipse"
apply plugin: 'maven-publish'
apply plugin: 'net.minecraftforge.gradle'

version = modVersion
group = 'chappie.theboys'
archivesBaseName = 'TheBoys'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20200916-1.16.2'
	
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            mods {
                theboys {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            mods {
                theboys {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'theboys', '--all', '--output', file('src/generated/resources/')
            mods {
                theboys {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven {
        url "https://jitpack.io/"
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.16.3-34.1.33'
    compile 'me.cameronwhyte.gitlab.grillo78:heroes-united:82dc156265:deobf'
    implementation 'com.github.Vatuu:discord-rpc:1.6.2'
}
