# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.4
loader_version=0.16.5
# Mod Properties
mod_version=1.0.0
maven_group=chappie.theboys
archives_base_name=theboys
# Dependencies
fabric_version=0.97.2+1.20.4

mixin_extras_version = 0.5.0-beta.1
mixin_version = 0.8.7
cca_version=5.4.0
geckolib_version=4.4.4
cloth_config_version=13.0.121
fcap_version=20.4.3
veil_version=1.0.0.43
modulus_version=1.0.0
