# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.17.2
# Mod Properties
mod_version=1.0
maven_group=chappie.theboys
archives_base_name=theboys
# Dependencies
fabric_version=0.92.6+1.20.1

mixin_extras_version = 0.5.0
cca_version=5.2.3
geckolib_version = 4.7.3
fcap_version=8.0.2
modulus_version=1.1