# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
parchment_version=2025.10.12
loader_version=0.17.3
# Mod Properties
mod_version=1.0.3
maven_group=chappie.theboys
archives_base_name=theboys
# Dependencies
fabric_version=0.136.0

mixin_extras_version=0.5.0
cca_version=7.2.0
mod_menu_version=16.0.0-rc.1
geckolib_version=5.3-alpha-3
fcap_version=21.10.0
modulus_version=1.0.0
sodium_version=mc1.21.10-0.7.2-fabric
