pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
    }
}

includeBuild('../Modulus') {
    dependencySubstitution {
        substitute module('chappie.modulus:modulus') using project(':')
    }
}
