pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'TheBoys'

includeBuild('D:/McModding/Modulus') {
    dependencySubstitution {
        substitute module('chappie.modulus:modulus') using project(':')
    }
}
