modLoader="javafml"
loaderVersion="[34,)"
license="All right reserved"

[[mods]]
modId="theboys"
version="0.1"
displayName="Heroes United: The Boys"
authors="Chappie"
description="The Boys is part of the Amazon Prime series!"

[[dependencies.theboys]]
   modId="heroesunited"
   mandatory=true
   versionRange="2,"
   ordering="AFTER"
   side="BOTH"
