modLoader="javafml" 
loaderVersion="[49,)"
license="All rights reserved"

[[mods]]
modId="theboys"
version="${file.jarVersion}"
displayName="The Boys"
logoFile="theboys.png"
credits="Thanks to BizDC for skins"
authors="Chappie"
description='''"The Boys" mod, is based on the series of the same name, allows players to get into the role of superheroes. It includes suits, weapons and abilities inspired by the world of The Boys. This will enrich the gaming experience of fans of the series, allowing them to play as characters from this series.'''
[[dependencies.theboys]]
    modId="forge" 
    mandatory=true
    versionRange="[49,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theboys]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
